### ISSUE TITLE
Few stuff but mainly to thanks you

### ISSUE THREAD

**Issue by thierry75** [diwi/PS3Eye#2]
Hi, first thanks for releasing this, i waited a solution for ps3eye on mac so badly...
you made my day
Just 2 comments, everything works fine but the vertical flip give a strange picture, sort of rgb mess...
its not a big deal for me, just to let you know
the other point is more like a request, i want to use on some project the fast mode of the cam, 320x240 at 120fps
sorry if it s already possible to do that but i didn't found it
Again, thanks a lot for sharing

**Comment by diwi** [comment]
Hi, thanks for the feedback. I updated the library.
QVGA is supported now and the vertical flip glitch should also be fixed.
```
    PS3Eye.Resolution.VGA  ... framerate[2,  75]
    PS3Eye.Resolution.QVGA ... framerate[2, 187]
```

you can use `printAvailableConfigs()` to see what framerate is supported at what resolution.

the "PS3Eye_GUI" example also got an update to switch between some given presets.
https://github.com/diwi/PS3Eye/blob/master/examples/ProcessingDemo/PS3Eye_GUI/PS3Eye_GUI.java

**Comment by thierry75** [comment]
HI,
everything works fine
...your code is going underwater for a plankton survey on mediterranean sea...
Thanks
